// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRljO1EtiVISFGdZMMzgxwQIOPkMss-mU',
    appId: '1:100430266946:web:29bd6cd98326a1e58f63db',
    messagingSenderId: '100430266946',
    projectId: 'maturaappai',
    authDomain: 'maturaappai.firebaseapp.com',
    storageBucket: 'maturaappai.firebasestorage.app',
    measurementId: 'G-FMXG1MR4L6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWn_uT3e_f9EEskg7tv8H8p2PXwLT7n6U',
    appId: '1:100430266946:android:9b979e7e6c47f7538f63db',
    messagingSenderId: '100430266946',
    projectId: 'maturaappai',
    storageBucket: 'maturaappai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE7-YntyUzhOgf7HEuqMuQJlEKmH6MH3Y',
    appId: '1:100430266946:ios:0b336ca5da5c69168f63db',
    messagingSenderId: '100430266946',
    projectId: 'maturaappai',
    storageBucket: 'maturaappai.firebasestorage.app',
    iosClientId: '100430266946-rta3af8dgg8vdl4o42qrepvs5flqrhvu.apps.googleusercontent.com',
    iosBundleId: 'com.example.maturaAppFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE7-YntyUzhOgf7HEuqMuQJlEKmH6MH3Y',
    appId: '1:100430266946:ios:0b336ca5da5c69168f63db',
    messagingSenderId: '100430266946',
    projectId: 'maturaappai',
    storageBucket: 'maturaappai.firebasestorage.app',
    iosClientId: '100430266946-rta3af8dgg8vdl4o42qrepvs5flqrhvu.apps.googleusercontent.com',
    iosBundleId: 'com.example.maturaAppFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRljO1EtiVISFGdZMMzgxwQIOPkMss-mU',
    appId: '1:100430266946:web:fedbec4bb97ebe158f63db',
    messagingSenderId: '100430266946',
    projectId: 'maturaappai',
    authDomain: 'maturaappai.firebaseapp.com',
    storageBucket: 'maturaappai.firebasestorage.app',
    measurementId: 'G-CBP45MV4P2',
  );
}
